/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    ILAddItem: typeof import('./src/components/ILAddItem.vue')['default']
    ILAutoComplete: typeof import('./src/components/primevue/ILAutoComplete.vue')['default']
    ILAvatar: typeof import('./src/components/primevue/ILAvatar.vue')['default']
    ILBookCover: typeof import('./src/components/ILBookCover.vue')['default']
    ILBoxButton: typeof import('./src/components/ILBoxButton.vue')['default']
    ILDatePicker: typeof import('./src/components/primevue/ILDatePicker.vue')['default']
    ILDivider: typeof import('./src/components/ILDivider.vue')['default']
    ILDrawer: typeof import('./src/components/primevue/ILDrawer.vue')['default']
    ILIconButton: typeof import('./src/components/primevue/ILIconButton.vue')['default']
    ILImageUploader: typeof import('./src/components/primevue/ILImageUploader.vue')['default']
    ILNumberInput: typeof import('./src/components/primevue/ILNumberInput.vue')['default']
    ILQuotes: typeof import('./src/components/quote/ILQuotes.vue')['default']
    ILQuoteSmall: typeof import('./src/components/quote/ILQuoteSmall.vue')['default']
    ILRating: typeof import('./src/components/primevue/ILRating.vue')['default']
    ILSelect: typeof import('./src/components/primevue/ILSelect.vue')['default']
    ILSelectButton: typeof import('./src/components/primevue/ILSelectButton.vue')['default']
    ILTextArea: typeof import('./src/components/primevue/ILTextArea.vue')['default']
    ILTextButton: typeof import('./src/components/primevue/ILTextButton.vue')['default']
    ILTextInput: typeof import('./src/components/primevue/ILTextInput.vue')['default']
    ILToggleSwitch: typeof import('./src/components/primevue/ILToggleSwitch.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    Quotes: typeof import('./src/components/Quotes.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
